### ISSUE TITLE
Cluster file empty

### ISSUE THREAD

**Issue by papelypluma** [zwang-bioinformatics/GOGO#3]
Hi GOGO developers, thank you for sharing this tool. I would like to seek for your help. I'm running the gene_list_comb.pl, and it's running without errors. However, the cluster file output is empty. There are also no errors. I was wondering if there are pointers I can follow to address this semantic issue. Thank you!

**Comment by czhao2** [comment]
The clusters are calculated based on one ontology. Try to confirm that every gene has at least one annotated GO term for an ontology. If a gene isn't annotated with a GO term from the ontology, remove the gene and rerun the clustering algorithm.

**Comment by papelypluma** [comment]
Hi @czhao2, thank you for suggesting this. I checked that each gene has at least one annotated GO term, but the tool still outputs an empty cluster file. I'm sharing the input file that I'm trying to cluster here. 

Edit: I'm using the standalone version of GOGO, and I'm getting a non-empty output file <output.file>. I tried submitting the file online, but I didn't work.

[pw_gogo.input.txt](https://github.com/zwang-bioinformatics/GOGO/files/8009290/pw_gogo.input.txt)

Thank you.

**Comment by czhao2** [comment]
Thanks for choosing GOGO! Please check GO terms independently for each ontology (BPO, CCO, or MFO). In other words, if you want to calculate the cluster based on CCO, you need functional similarities between every two genes.

I found an example from the file you provided. Since gene: mAjapPCC1103 only has GO:0005634 (CCO), you can only expect the clusters generated based on CCO gene functional similarities. However, you also have gene: nbisL1mrna1309 with an MFO GO:0003676. You cannot get clusters based on this file.

**Comment by papelypluma** [comment]
Thanks for the pointers @czhao2!
